python3 HeifER/process_heif.py ~/samples/conformance_files/C001.heic -outdir ~/samples/processed/conformance_files/C001.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C002.heic -outdir ~/samples/processed/conformance_files/C002.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C003.heic -outdir ~/samples/processed/conformance_files/C003.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C004.heic -outdir ~/samples/processed/conformance_files/C004.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C005.heic -outdir ~/samples/processed/conformance_files/C005.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C006.heic -outdir ~/samples/processed/conformance_files/C006.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C007.heic -outdir ~/samples/processed/conformance_files/C007.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C008.heic -outdir ~/samples/processed/conformance_files/C008.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C009.heic -outdir ~/samples/processed/conformance_files/C009.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C010.heic -outdir ~/samples/processed/conformance_files/C010.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C011.heic -outdir ~/samples/processed/conformance_files/C011.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C012.heic -outdir ~/samples/processed/conformance_files/C012.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C013.heic -outdir ~/samples/processed/conformance_files/C013.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C014.heic -outdir ~/samples/processed/conformance_files/C014.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C015.heic -outdir ~/samples/processed/conformance_files/C015.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C016.heic -outdir ~/samples/processed/conformance_files/C016.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C017.heic -outdir ~/samples/processed/conformance_files/C017.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C018.heic -outdir ~/samples/processed/conformance_files/C018.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C019.heic -outdir ~/samples/processed/conformance_files/C019.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C020.heic -outdir ~/samples/processed/conformance_files/C020.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C021.heic -outdir ~/samples/processed/conformance_files/C021.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C022.heic -outdir ~/samples/processed/conformance_files/C022.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C023.heic -outdir ~/samples/processed/conformance_files/C023.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C024.heic -outdir ~/samples/processed/conformance_files/C024.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C025.heic -outdir ~/samples/processed/conformance_files/C025.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C026.heic -outdir ~/samples/processed/conformance_files/C026.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C027.heic -outdir ~/samples/processed/conformance_files/C027.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C028.heic -outdir ~/samples/processed/conformance_files/C028.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C029.heic -outdir ~/samples/processed/conformance_files/C029.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C030.heic -outdir ~/samples/processed/conformance_files/C030.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C031.heic -outdir ~/samples/processed/conformance_files/C031.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C032.heic -outdir ~/samples/processed/conformance_files/C032.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C033.heic -outdir ~/samples/processed/conformance_files/C033.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C034.heic -outdir ~/samples/processed/conformance_files/C034.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C035.heic -outdir ~/samples/processed/conformance_files/C035.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C036.heic -outdir ~/samples/processed/conformance_files/C036.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C037.heic -outdir ~/samples/processed/conformance_files/C037.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C038.heic -outdir ~/samples/processed/conformance_files/C038.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C039.heic -outdir ~/samples/processed/conformance_files/C039.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C040.heic -outdir ~/samples/processed/conformance_files/C040.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C041.heic -outdir ~/samples/processed/conformance_files/C041.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C042.heic -outdir ~/samples/processed/conformance_files/C042.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C043.heic -outdir ~/samples/processed/conformance_files/C043.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C044.heic -outdir ~/samples/processed/conformance_files/C044.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C045.heic -outdir ~/samples/processed/conformance_files/C045.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C046.heic -outdir ~/samples/processed/conformance_files/C046.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C047.heic -outdir ~/samples/processed/conformance_files/C047.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C048.heic -outdir ~/samples/processed/conformance_files/C048.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C049.heic -outdir ~/samples/processed/conformance_files/C049.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C050.heic -outdir ~/samples/processed/conformance_files/C050.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C051.heic -outdir ~/samples/processed/conformance_files/C051.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C052.heic -outdir ~/samples/processed/conformance_files/C052.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/C053.heic -outdir ~/samples/processed/conformance_files/C053.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/MIAF001.heic -outdir ~/samples/processed/conformance_files/MIAF001.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/MIAF002.heic -outdir ~/samples/processed/conformance_files/MIAF002.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/MIAF003.heic -outdir ~/samples/processed/conformance_files/MIAF003.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/MIAF004.heic -outdir ~/samples/processed/conformance_files/MIAF004.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/MIAF005.heic -outdir ~/samples/processed/conformance_files/MIAF005.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/MIAF006.heic -outdir ~/samples/processed/conformance_files/MIAF006.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/MIAF007.heic -outdir ~/samples/processed/conformance_files/MIAF007.heic.export
python3 HeifER/process_heif.py ~/samples/conformance_files/multilayer001.heic -outdir ~/samples/processed/conformance_files/Mmultilayer001.heic
python3 HeifER/process_heif.py ~/samples/conformance_files/multilayer002.heic -outdir ~/samples/processed/conformance_files/Mmultilayer002.heic
python3 HeifER/process_heif.py ~/samples/conformance_files/multilayer003.heic -outdir ~/samples/processed/conformance_files/Mmultilayer003.heic
python3 HeifER/process_heif.py ~/samples/conformance_files/multilayer004.heic -outdir ~/samples/processed/conformance_files/Mmultilayer004.heic
python3 HeifER/process_heif.py ~/samples/conformance_files/multilayer005.heic -outdir ~/samples/processed/conformance_files/Mmultilayer005.heic
